[profile.default]
src = 'src/contracts'
out = 'forge-out'
libs = ['node_modules']
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
constant_optimizer = true

remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/'
]

